# apiVersion: v1 
# kind: Secret 
# metadata:
#   name:  aws-cred
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: | 
#      "ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICIxODY4MzcyMjMxMzkuZGtyLmVjci5ldS1ub3J0aC0xLmFtYXpvbmF3cy5jb20iOiB7fSwKICAgICAgICAgICAgICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQogICAgICAgIH0sCiAgICAgICAgImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCiAgICAgICAgImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiLAogICAgICAgICJwbHVnaW5zIjogewogICAgICAgICAgICAgICAgIi14LWNsaS1oaW50cyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImVuYWJsZWQiOiAidHJ1ZSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0="
# ---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: finance-api
  labels:
    app: finance-api 
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: finance-api
  template:
    metadata: 
      labels:
        app: finance-api
    spec:
      containers:
        - name: finance-api 
          image: public.ecr.aws/v7e4g1x6/finance-api:40
          imagePullPolicy: Always
          ports:
            - containerPort: 3000